---
title: "Patent_citation"
author: "Koji Higuchi"
date: "October. 9th, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

#
library(magrittr)
library(tidyverse)

#
class_mean <- readr::read_csv("C://Users/Koji/Orbis/patent_citation_mean.csv")

section_titles <- c("Human Necessities", "Perofrming Operations; Transporting",
                    "Chemistry; Merallurgy", "Textiles; Paper", "Fixed Constructions",
                    "Mechanical Engineering", "Physics", "Electricity")
            
class_mean %<>%
  filter(class %in% LETTERS[1:8]) %>% 
  mutate(class = as.factor(class))

levels(class_mean$class) <- section_titles 

```

## Average # of Citation Recieved by year  

```{r echo=F}
class_mean %>% ggplot(aes(pubyear, V1)) +
  geom_line(aes(colour = class)) +
  ggthemes::scale_colour_tableau() +
  ggthemes::theme_calc() + 
  ylab("Average # of Citation Recieved") + xlab("Publication Year") -> p1

plotly::ggplotly(p1)

```
  

## Heatmap version
```{r echo=F}

class_mean %>%
  arrange(desc(pubyear)) %>%
  spread(pubyear, V1) %>%
  select(-class) %>% 
d3heatmap::d3heatmap(labRow = section_titles, Colv = F,
          colors = "Blues")
```
